name: e_commerce_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'






dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Backend Specific
  dartz: ^0.10.1
  equatable: ^2.0.5

  # UnitTest Specific
  test: ^1.24.9
  mocktail: ^1.0.3

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/reviews/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Light.ttf
         weight: 300
       - asset: assets/fonts/Poppins-LightItalic.ttf
         weight: 300
         style: italic
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 400
       - asset: assets/fonts/Poppins-Italic.ttf
         style: italic
       - asset: assets/fonts/Poppins-Medium.ttf
         weight: 500
       - asset: assets/fonts/Poppins-MediumItalic.ttf
         weight: 500
         style: italic
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
         weight: 600
         style: italic
       - asset: assets/fonts/Poppins-Bold.ttf
         weight: 800
       - asset: assets/fonts/Poppins-BoldItalic.ttf
         weight: 800
         style: italic


  
  
  
  
  
  
  
  
  
  
  
  
